steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - '--destination=us-docker.pkg.dev/$PROJECT_ID/frontend/explore:next'
      - '--cache=true'
      - '--cache-ttl=168h'
      - '--snapshotMode=redo'
      - '--use-new-run'
options:
  machineType: 'E2_HIGHCPU_32'
  diskSizeGb: 100
timeout: '3600s'
