FROM node:22-alpine
WORKDIR /app
COPY .next/standalone ./
COPY .next/static .next/static
COPY public public
COPY scripts/download-external-assets.sh scripts/
COPY scripts/validate-envs.sh scripts/
COPY configs/envs configs/envs
COPY entrypoint.sh .
RUN chmod +x entrypoint.sh scripts/*.sh
ENV PORT=3000 HOSTNAME=0.0.0.0
EXPOSE 3000
ENTRYPOINT ["./entrypoint.sh"]
